### ISSUE TITLE
Github Authentication flow changed.

### ISSUE THREAD

**Issue by thekayness** [learn-co-curriculum/rails-github-api#10]
The user first gets directed here: GET https://github.com/login/oauth/authorize
with the client id and redirect uri.

Then, github redirects BACK to the app if the user accepts with a code in the params, we then have to 
POST https://github.com/login/oauth/access_token with the code as part of the params to get the access token.

**Comment by DanielSeehausen** [comment]
Hi there,

After completing the lab, I found the authentication flow to be up to date with GitHub's. It could very well be that we have since updated the code to be compatible, or perhaps I am misunderstanding and there is something else being described here. 

Would you mind providing a bit more detail about the issue? Things that are especially useful:

An expanded explanation of what's going on.
Steps to reproduce the issue.
Details about your environment.
What's your operating system? Which version?
Are you using the Learn IDE or a local development environment?
A stack trace of any errors.
Thanks! 💙
