### ISSUE TITLE
I'm getting an error that real HTTP requests aren't allowed, so the tests don't pass even though I can see it working in my localhost browser

### ISSUE THREAD

**Issue by ldgarber** [learn-co-curriculum/rails-github-api#11]
Failure/Error: visit '/'
     WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: GET https://api.github.com/users//repos with headers {'Accept'=>'application/json', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Authorization'=>'token 1', 'User-Agent'=>'Faraday v0.9.1'}
       
       You can stub this request with the following snippet:
       
       stub_request(:get, "https://api.github.com/users//repos").
         with(:headers => {'Accept'=>'application/json', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Authorization'=>'token 1', 'User-Agent'=>'Faraday v0.9.1'}).
         to_return(:status => 200, :body => "", :headers => {})
       
       registered request stubs:
       
       stub_request(:post, "https://api.github.com/user/repos").
         with(:body => {"{\"name\":\"a-new-repo\"}"=>true},
              :headers => {'Authorization'=>'token 1'})
       stub_request(:get, "https://api.github.com/user").
         with(:headers => {'Authorization'=>'token 1'})
       stub_request(:post, "https://github.com/login/oauth/access_token").
         with(:body => {"client_id"=>nil, "client_secret"=>nil, "code"=>"20"},
              :headers => {'Accept'=>'application/json'})
       stub_request(:get, "https://api.github.com/user/repos").
         with(:headers => {'Authorization'=>'token 1'})

**Comment by kjleitz** [comment]
+1 same here

**Comment by mdo5004** [comment]
+1

**Comment by mdo5004** [comment]
I was failing the test `authentication displays the username on the page` with 
```
resp = Faraday.post("https://github.com/login/oauth/access_token") do |req|
    req.params['client_id'] = ENV['GITHUB_CLIENT']
    req.params['client_secret'] = ENV['GITHUB_SECRET']
    req.params['code'] = params[:code]
    req.headers['Accept'] = 'application/json'
end
```
But I passed with 
```
resp = Faraday.post("https://github.com/login/oauth/access_token") do |req|
            req.body = {"client_id": ENV['GITHUB_CLIENT'],
            "client_secret": ENV['GITHUB_SECRET'], 
            "code": params[:code]}
            req.headers['Accept'] = 'application/json'
end
```

In the curriculum, we are [repeatedly shown examples](https://github.com/learn-co-curriculum/web-auth-readme) like
```
  resp = Faraday.get("https://foursquare.com/oauth2/access_token") do |req|
    req.params['client_id'] = ENV['FOURSQUARE_CLIENT_ID']
    req.params['client_secret'] = ENV['FOURSQUARE_SECRET']
    req.params['grant_type'] = 'authorization_code'
    req.params['redirect_uri'] = "http://localhost:3000/auth"
    req.params['code'] = params[:code]
  end
```

So it only makes sense that I would construct my GET request in the way I show above, given the examples I've been shown. The test should be rewritten to anticipate students following the example of the curriculum, or vice versa.

**Comment by kyleblee** [comment]
+1 for the `WebMock::NetConnectNotAllowedError`

**Comment by itzsaga** [comment]
Just had a student run into this same thing using  the Cloud9 IDE.

**Comment by DanielSeehausen** [comment]
Hi there everyone!

Raising issues on GitHub should be reserved for problems with the curriculum — not difficulties solving a lab or proper error handling. Please take a look at the registered request stubs in your spec file and closely compare them to the error message. Please examine the url in the opening issue comment in this thread: `Unregistered request: GET https://api.github.com/users//repos `

The issue here appears to be with your own code. If the error messages in the test suite are not providing enough information for you to diagnose the problem, try the following three things:

Run your code as it is intended to be run. That is, don't simply rely on the test suite to check the functionality of your code — check it yourself! For Ruby code, add some lines to the bottom of the file that call your methods and output verifiable information to the terminal. For Sinatra or Rails applications, fire up your local server and try executing the same actions that the test suite is failing to complete. For JavaScript code, open up your browser's JS console, paste in your code, and play around with your functions and variables.
Use Pry to poke around your Ruby (or Sinatra), Rails, or JavaScript code step-by-step. Check that the values of particular variables are what you expect them to be at various points throughout the program's execution.
Use the Ask a Question (AAQ) feature, where the Technical Coaches (on supported tracks) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out this helpful article in the Learn Help Center.
If, after reviewing your code and consulting AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
