### ISSUE TITLE
test failure

### ISSUE THREAD

**Issue by jcpny1** [learn-co-curriculum/rails-github-api#12]
Failures:

  1) authentication displays the username on the page
     Failure/Error: visit '/auth?code=20'
     WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: GET https://github.com/login/oauth/access_token?client_id=90401f8e73a3cd4cd146&client_secret=2fc384774296494c75b45f3bb02c2ac5876c422c&code=20 with headers {'Accept'=>'application/json', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Faraday v0.9.1'}
       
       You can stub this request with the following snippet:
       
       stub_request(:get, "https://github.com/login/oauth/access_token?client_id=90401f8e73a3cd4cd146&client_secret=2fc384774296494c75b45f3bb02c2ac5876c422c&code=20").
         with(:headers => {'Accept'=>'application/json', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Faraday v0.9.1'}).
         to_return(:status => 200, :body => "", :headers => {})
       
       registered request stubs:
       
       stub_request(:post, "https://api.github.com/user/repos").
         with(:body => {"{\"name\":\"a-new-repo\"}"=>true},
              :headers => {'Authorization'=>'token 1'})
       stub_request(:get, "https://api.github.com/user").
         with(:headers => {'Authorization'=>'token 1'})
       stub_request(:post, "https://github.com/login/oauth/access_token").
         with(:body => {"client_id"=>nil, "client_secret"=>nil, "code"=>"20"},
              :headers => {'Accept'=>'application/json'})
       stub_request(:get, "https://api.github.com/user/repos").
         with(:headers => {'Authorization'=>'token 1'})
       
# ./spec/features/repos_spec.rb:5:in `block (2 levels) in <top (required)>'

**Comment by DanielSeehausen** [comment]
Hi there @jcpny1,

Raising issues on GitHub should be reserved for problems with the curriculum — not difficulties solving a lab or proper error handling. Please take a look at the registered request stubs in your spec file and closely compare them to the error message.

The issue here appears to be with your own code. If the error messages in the test suite are not providing enough information for you to diagnose the problem, try the following three things:

Run your code as it is intended to be run. That is, don't simply rely on the test suite to check the functionality of your code — check it yourself! For Ruby code, add some lines to the bottom of the file that call your methods and output verifiable information to the terminal. For Sinatra or Rails applications, fire up your local server and try executing the same actions that the test suite is failing to complete. For JavaScript code, open up your browser's JS console, paste in your code, and play around with your functions and variables.
Use Pry to poke around your Ruby (or Sinatra), Rails, or JavaScript code step-by-step. Check that the values of particular variables are what you expect them to be at various points throughout the program's execution.
Use the Ask a Question (AAQ) feature, where the Technical Coaches (on supported tracks) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out this helpful article in the Learn Help Center.
If, after reviewing your code and consulting AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙

**Comment by jcpny1** [comment]
Hi Daniel,
I was just reporting that the test code provided with this lab was in error. It appears to have been fixed with https://github.com/learn-co-curriculum/rails-github-api/commit/bc83485378aed0488299012005589a1b3ff81ecb on 15-Sep-2017.
Don't know if faulty code is a curriculum problem or not.
Regards,
John

**Comment by morgvanny** [comment]
If we are intending on students needing to change code in the spec files, we should probably mention that in the readme, as we almost never have anyone modify those files. Even if we did intend that, we should probably fix our solution branch so that all of the tests pass, as that's the pattern we've established for all of our other labs.
