### ISSUE TITLE
session key must be `session[:token]`

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/rails-github-api#5]
I spent hours trying to debug this with the nice people on ask a question. I was setting my session in the controller to `session[:gh_token]` because I thought it would be good to specify. Resulting error:

```
visiting root
  lists repos (FAILED - 1)

Failures:

  1) visiting root lists repos
     Failure/Error: visit '/'
     ActionController::RoutingError:
       No route matches [GET] "/login/oauth/authorize"
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/web-console-2.1.3/lib/web_console/middleware.rb:37:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/railties-4.2.1/lib/rails/rack/logger.rb:38:in `call_app'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `block in call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in `tagged'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.1/lib/action_dispatch/middleware/static.rb:113:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/railties-4.2.1/lib/rails/application.rb:164:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/capybara-2.4.4/lib/capybara/rack_test/browser.rb:60:in `process'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/capybara-2.4.4/lib/capybara/rack_test/browser.rb:38:in `block in process_and_follow_redirects'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/capybara-2.4.4/lib/capybara/rack_test/browser.rb:37:in `times'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/capybara-2.4.4/lib/capybara/rack_test/browser.rb:37:in `process_and_follow_redirects'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/capybara-2.4.4/lib/capybara/rack_test/browser.rb:21:in `visit'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/capybara-2.4.4/lib/capybara/rack_test/driver.rb:42:in `visit'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/capybara-2.4.4/lib/capybara/session.rb:227:in `visit'
     # /Users/Roberto/.rvm/gems/ruby-2.2.3/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/features/repos_spec.rb:16:in `block (2 levels) in <top (required)>'

Finished in 0.31637 seconds (files took 3.1 seconds to load)
2 examples, 1 failure
```

This is not an easy bug to catch. It would mean the world to students to students like me to know that the session token must be named [:token], or the test won't work. 

Just to clarify, any key name works perfectly in the browser. The only way I found the answer was because `repos_spec.rb:23` reads:

```
describe "new repo form" do
  before :each do
    page.set_rack_session(:token => "1")
  end
```

Again, a really hard bug to catch...

**Comment by MitulMistry** [comment]
It also appears that the environment variables need to be named GITHUB_CLIENT and GITHUB_SECRET in order to pass the tests. I had them named differently and it gave me an error: 
`Failure/Error: visit '/auth?code=20'
     WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request:

**Comment by DanielSeehausen** [comment]
Thank you for bringing this to our attention!
The spec has since been changed. In addition, interpreting the specs when they expect a specific variable name is an important part of learning TTD. Because we can't assume the variable name students will choose, one must be provided, leading us to go with the generics: "token", "GITHUB_CLIENT", "GITHUB_SECRET"

Raising issues on GitHub should be reserved for problems with the curriculum — not difficulties solving a lab.

The issue here appears to be with your own code. If the error messages in the test suite are not providing enough information for you to diagnose the problem, try the following three things:

Run your code as it is intended to be run. That is, don't simply rely on the test suite to check the functionality of your code — check it yourself! For Ruby code, add some lines to the bottom of the file that call your methods and output verifiable information to the terminal. For Sinatra or Rails applications, fire up your local server and try executing the same actions that the test suite is failing to complete. For JavaScript code, open up your browser's JS console, paste in your code, and play around with your functions and variables.
Use Pry to poke around your Ruby (or Sinatra), Rails, or JavaScript code step-by-step. Check that the values of particular variables are what you expect them to be at various points throughout the program's execution.
Use the Ask a Question (AAQ) feature, where the Technical Coaches (on supported tracks) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out this helpful article in the Learn Help Center.
If, after reviewing your code and consulting AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
